global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # 1. Auto‑discover every container that sets labels
  #      metrics.scrape=true
  #      metrics.port=<port>
  #      metrics.path=/metrics (optional)
  - job_name: 'docker_sd'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_metrics_scrape]
        regex: true
        action: keep
     
